# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YHCaptureCar' do
    #    pod 'SBJson', '~> 3.1.1'
    #    pod 'RongCloudIMKit', '2.6.7'
    pod 'sqlite3', '3.22.0'
    #pod 'RongCloudIMLib', '2.6.7'
    pod 'AFNetworking', '3.1.0'
    pod 'SDWebImage', '3.8.1'
    #    pod 'JSPatch', '1.1'
    pod 'MBProgressHUD', '1.1.0'
    #    pod 'BaiduMapKit', '3.0.0'
    pod 'UITableView+FDTemplateLayoutCell', '1.4.0'
    pod 'SVProgressHUD', '2.0.3'
    pod 'DAContextMenuTableViewController', '1.0.3'
    pod 'MJRefresh', '3.1.12'
    
    pod 'SDCycleScrollView', '1.65'
    
    pod 'MarqueeLabel', '2.7.8'
    pod 'MARKRangeSlider', '1.1.0'
    pod 'HUPhotoBrowser', '1.1.3'
    pod 'Masonry', '1.1.0'
    pod 'TTTAttributedLabel', '2.0.0'
    pod 'PinYin4Objc', '1.1.1'
    pod 'IQKeyboardManager', '5.0.7'
    
    pod 'MJExtension', '3.0.13'
    
    #pod 'FMDB', '2.7.2'
    
    pod 'BRPickerView', '~> 2.1.0'    #各种选择器一个就够了,日期选择器、时间选择器、地址选择器、自定义字符串选择器。
    
    #高德地图相关
    #    pod 'AMap3DMap', '~>4.4.1'
    pod 'AMapSearch', '6.9.0' #搜索服务SDK
    pod 'AMapLocation', '2.6.2'
    pod 'AMapNavi','6.9.0'#这个要放到其他高德sdk后
    pod 'JZLocationConverter'#gps纠偏
    pod 'LYEmptyView','1.1.0'#空白页面占位图（无数据、无网络占位图）
    
 #友盟分享 适配系统13版本
 pod 'UMCCommon','2.1.1'#,'2.0.1'#,'1.4.1'#基础库
 pod 'UMCSecurityPlugins','1.0.6'#,'1.0.6'#基础库:pod 'UMCSecurityPlugins'为安全组件，不需要开发者显式调用，为开发者提供安全的数据环境，能有效的防止刷量和反作弊等行为，属于可选项，如果对App的数据安全性要求不高的话，可以去掉此pod
 pod 'UMCShare/UI','6.9.6'#,'6.9.5'#,'6.8.1' #UI模块（分享面板，建议添加）
 pod 'UMCShare/Social/ReducedWeChat','6.9.6'#,'6.9.5'#,'6.8.1'#集成微信(精简版0.2M)
 pod 'UMCShare/Social/ReducedQQ','6.9.6'#,'6.9.5'#,'6.8.1'# 集成QQ/QZone/TIM(精简版0.5M)

   pod 'Bugly', '2.5.0'
    
    pod 'JPush', '3.1.0'

end



