# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'penco' do
    pod 'AFNetworking', '3.1.0'
    pod 'SDWebImage', '5.0.0'
    pod 'MBProgressHUD', '1.1.0'
    pod 'SVProgressHUD', '2.0.3'
    pod 'MJRefresh', '3.1.12'
    pod 'SDCycleScrollView', '1.80'
    pod 'HUPhotoBrowser', '1.1.3'
    pod 'Masonry', '1.1.0'
    pod 'IQKeyboardManager'#, '4.0.4'

    pod 'MJExtension', '3.0.13'
    pod 'SAMKeychain', '1.5.3'
    #友盟分享
    pod 'UMCCommon'#基础库
#    pod 'UMCSecurityPlugins'#基础库:pod 'UMCSecurityPlugins'为安全组件，不需要开发者显式调用，为开发者提供安全的数据环境，能有效的防止刷量和反作弊等行为，属于可选项，如果对App的数据安全性要求不高的话，可以去掉此pod
    pod 'UMCShare/UI' #UI模块（分享面板，建议添加）
    pod 'UMCShare/Social/ReducedWeChat'#集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedQQ'# 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedSina'# 集成新浪微博(精简版1M)

    pod 'BabyBluetooth'#蓝牙中间键
#    pod 'Bugly', '~> 2.5.0'
  pod 'TYCyclePagerView'
  pod 'AAChartKit', :git => 'https://github.com/AAChartModel/AAChartKit.git'

  pod 'MQTTClient', '0.8.5'
  pod 'WechatOpenSDK'
  pod 'CocoaLumberjack'
end



